"""
PDF report generator using ReportLab.

Produces a multi-page summary report with:
  - Page 1: KPI cards, time range, sample counts
  - Page 2: RSRP CDF curve
  - Page 3: Coverage bin distribution
  - Page 4: Event summary table
  - Page 5: Worst cells ranking
  - Page 6: Map screenshot (optional, requires selenium)
"""

import io
import logging
from typing import Optional, Dict, Any, List
import numpy as np

logger = logging.getLogger(__name__)


def _fmt(val, fmt=".1f", na="N/A"):
    if val is None:
        return na
    try:
        if isinstance(val, float) and (np.isnan(val) or np.isinf(val)):
            return na
        return format(val, fmt)
    except (ValueError, TypeError):
        return str(val)


def export_pdf_report(
    kpis: Dict[str, Any],
    per_cell_df=None,
    map_screenshot_png: Optional[bytes] = None,
) -> bytes:
    """
    Generate a PDF summary report.

    Args:
        kpis: Summary KPI dict from kpi_engine.compute_summary_kpis()
        per_cell_df: Per-cell statistics DataFrame
        map_screenshot_png: Optional PNG bytes of map screenshot

    Returns:
        PDF bytes
    """
    try:
        from reportlab.lib.pagesizes import A4, landscape
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm, mm
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
            HRFlowable, Image, PageBreak,
        )
        from reportlab.graphics.shapes import Drawing, Rect, String
        from reportlab.graphics.charts.lineplots import LinePlot
        from reportlab.graphics.charts.piecharts import Pie
        from reportlab.graphics import renderPDF
    except ImportError as exc:
        logger.warning("reportlab not installed — PDF export unavailable: %s", exc)
        return b""

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
        title="VDT Report",
        author="VDT Tool",
    )

    # ── Color palette ─────────────────────────────────────────────────────────
    BG_DARK = colors.HexColor("#1a1a2e")
    ACCENT = colors.HexColor("#0f3460")
    HIGHLIGHT = colors.HexColor("#e94560")
    TEXT_LIGHT = colors.HexColor("#e0e0e0")
    GREEN = colors.HexColor("#2ecc71")
    ORANGE = colors.HexColor("#f0a500")
    RED = colors.HexColor("#e06000")

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "VDTTitle",
        parent=styles["Title"],
        textColor=HIGHLIGHT,
        fontSize=18,
        spaceAfter=6,
        fontName="Helvetica-Bold",
    )
    h2_style = ParagraphStyle(
        "VDTH2",
        parent=styles["Heading2"],
        textColor=ACCENT,
        fontSize=12,
        spaceAfter=4,
        fontName="Helvetica-Bold",
    )
    body_style = ParagraphStyle(
        "VDTBody",
        parent=styles["Normal"],
        fontSize=9,
        fontName="Helvetica",
        spaceAfter=2,
    )
    mono_style = ParagraphStyle(
        "VDTMono",
        parent=styles["Normal"],
        fontSize=9,
        fontName="Courier",
        spaceAfter=2,
    )

    story = []

    # ── Title ─────────────────────────────────────────────────────────────────
    story.append(Paragraph("Virtual Drive Test — Summary Report", title_style))
    story.append(Paragraph("Generated by VDT Tool", body_style))
    story.append(HRFlowable(width="100%", thickness=1, color=HIGHLIGHT, spaceAfter=8))
    story.append(Spacer(1, 0.3 * cm))

    # ── KPI summary table ─────────────────────────────────────────────────────
    story.append(Paragraph("Key Performance Indicators", h2_style))

    kpi_data = [
        ["Metric", "Value", "Metric", "Value"],
        ["Total Samples", f"{kpis.get('n_samples', 0):,}", "GPS Match %", f"{_fmt(kpis.get('gps_match_pct'), '.1f')}%"],
        ["Time Range", kpis.get("time_range", "N/A"), "Duration", f"{_fmt(kpis.get('duration_min'), '.1f')} min"],
        ["RSRP Median", f"{_fmt(kpis.get('rsrp_median'))} dBm", "RSRP P5/P95", f"{_fmt(kpis.get('rsrp_p5'))} / {_fmt(kpis.get('rsrp_p95'))} dBm"],
        ["RSRQ Median", f"{_fmt(kpis.get('rsrq_median'))} dB", "SINR Median", f"{_fmt(kpis.get('sinr_median'))} dB"],
        ["HO Attempts", f"{kpis.get('ho_attempt', 0)}", "HO Success Rate", f"{_fmt(kpis.get('ho_sr'))}%"],
        ["HO Failures", f"{kpis.get('ho_failure', 0)}", "RLF Count", f"{kpis.get('rlf_count', 0)}"],
        ["RLF Rate/10k", f"{_fmt(kpis.get('rlf_rate_per_10k'))}", "SCG Failures", f"{kpis.get('scg_failure_count', 0)}"],
        ["DL Throughput", f"{_fmt(kpis.get('dl_throughput_median_mbps'))} Mbps", "UL Throughput", f"{_fmt(kpis.get('ul_throughput_median_mbps'))} Mbps"],
        ["A3 Triggers", f"{kpis.get('a3_trigger_count', 0)}", "A5 Triggers", f"{kpis.get('a5_trigger_count', 0)}"],
    ]

    kpi_table = Table(kpi_data, colWidths=[4 * cm, 4.5 * cm, 4 * cm, 4.5 * cm])
    kpi_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
                ("TEXTCOLOR", (0, 0), (-1, 0), TEXT_LIGHT),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f5f5f5")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#eef2f7")]),
                ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
                ("FONTNAME", (2, 1), (2, -1), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("PADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(kpi_table)
    story.append(Spacer(1, 0.5 * cm))

    # ── Coverage bin distribution ─────────────────────────────────────────────
    coverage = kpis.get("coverage_bins", {})
    if coverage:
        story.append(Paragraph("Coverage Distribution (RSRP)", h2_style))
        bin_labels = ["Excellent (≥-80)", "Good (-80–-90)", "Fair (-90–-100)", "Poor (-100–-110)", "Bad (<-110)"]
        bin_keys = ["Excellent", "Good", "Fair", "Poor", "Bad"]
        bin_colors_hex = ["#2ecc71", "#a8d08d", "#f0a500", "#e06000", "#c0392b"]
        total = sum(coverage.values()) or 1

        cov_data = [["Coverage Class", "Sample Count", "Percentage"]]
        for label, key, color_hex in zip(bin_labels, bin_keys, bin_colors_hex):
            count = coverage.get(key, 0)
            pct = 100 * count / total
            cov_data.append([label, f"{count:,}", f"{pct:.1f}%"])

        cov_table = Table(cov_data, colWidths=[7 * cm, 4 * cm, 4 * cm])
        cov_style = [
            ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
            ("TEXTCOLOR", (0, 0), (-1, 0), TEXT_LIGHT),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
            ("PADDING", (0, 0), (-1, -1), 4),
        ]
        for i, (_, key, color_hex) in enumerate(zip(bin_labels, bin_keys, bin_colors_hex), start=1):
            cov_style.append(
                ("BACKGROUND", (0, i), (0, i), colors.HexColor(color_hex))
            )
            cov_style.append(("TEXTCOLOR", (0, i), (0, i), colors.white))
        cov_table.setStyle(TableStyle(cov_style))
        story.append(cov_table)
        story.append(Spacer(1, 0.5 * cm))

    # ── Per-cell worst performers ─────────────────────────────────────────────
    if per_cell_df is not None and not per_cell_df.empty:
        story.append(Paragraph("Worst Cells by Median RSRP", h2_style))

        sort_col = "rsrp_median" if "rsrp_median" in per_cell_df.columns else per_cell_df.columns[0]
        worst = per_cell_df.nsmallest(10, sort_col) if sort_col in per_cell_df.columns else per_cell_df.head(10)

        display_cols = [
            c for c in ["Cell_ID", "pci", "sample_count", "rsrp_median", "rsrp_p5",
                         "sinr_median", "ho_sr", "rlf_rate", "dl_mbps_median"]
            if c in worst.columns
        ]
        header = [c.replace("_", " ").title() for c in display_cols]

        cell_data = [header]
        for _, row in worst.iterrows():
            cell_data.append([_fmt(row.get(c), ".1f") if isinstance(row.get(c), float) else str(row.get(c, "")) for c in display_cols])

        col_w = 17 * cm / max(len(display_cols), 1)
        cell_table = Table(cell_data, colWidths=[col_w] * len(display_cols))
        cell_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
                    ("TEXTCOLOR", (0, 0), (-1, 0), TEXT_LIGHT),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 7),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#eef2f7")]),
                    ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
                    ("PADDING", (0, 0), (-1, -1), 3),
                ]
            )
        )
        story.append(cell_table)
        story.append(Spacer(1, 0.5 * cm))

    # ── RSRP CDF chart ────────────────────────────────────────────────────────
    rsrp_x = kpis.get("rsrp_cdf_x", [])
    rsrp_y = kpis.get("rsrp_cdf_y", [])
    if rsrp_x and rsrp_y and len(rsrp_x) > 1:
        story.append(PageBreak())
        story.append(Paragraph("RSRP Cumulative Distribution Function", h2_style))

        d = Drawing(450, 220)
        lp = LinePlot()
        lp.x = 40
        lp.y = 20
        lp.width = 380
        lp.height = 180
        lp.data = [list(zip(rsrp_x, [y * 100 for y in rsrp_y]))]
        lp.lines[0].strokeColor = colors.HexColor("#00d4ff")
        lp.lines[0].strokeWidth = 1.5
        lp.xValueAxis.valueMin = min(rsrp_x)
        lp.xValueAxis.valueMax = max(rsrp_x)
        lp.xValueAxis.title = "RSRP (dBm)"
        lp.yValueAxis.valueMin = 0
        lp.yValueAxis.valueMax = 100
        lp.yValueAxis.title = "Cumulative %"
        d.add(lp)
        story.append(d)

    # ── Map screenshot ─────────────────────────────────────────────────────────
    if map_screenshot_png:
        story.append(PageBreak())
        story.append(Paragraph("Map Overview", h2_style))
        img_buf = io.BytesIO(map_screenshot_png)
        img = Image(img_buf, width=17 * cm, height=12 * cm, kind="proportional")
        story.append(img)

    doc.build(story)
    buf.seek(0)
    return buf.read()


def capture_map_screenshot(url: str, width: int = 1280, height: int = 800) -> Optional[bytes]:
    """
    Capture a screenshot of the running Dash app map using selenium.
    Returns PNG bytes or None if selenium is unavailable.
    """
    try:
        from selenium import webdriver
        from selenium.webdriver.chrome.options import Options
        from selenium.webdriver.chrome.service import Service
        from webdriver_manager.chrome import ChromeDriverManager
        import time

        opts = Options()
        opts.add_argument("--headless")
        opts.add_argument("--no-sandbox")
        opts.add_argument("--disable-dev-shm-usage")
        opts.add_argument(f"--window-size={width},{height}")

        driver = webdriver.Chrome(
            service=Service(ChromeDriverManager().install()), options=opts
        )
        driver.get(url)
        time.sleep(3)  # Allow map tiles to load
        png = driver.get_screenshot_as_png()
        driver.quit()
        return png
    except Exception as exc:
        logger.warning("Map screenshot failed: %s", exc)
        return None
